#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio           0.6
bspc config focus_follows_pointer true
bspc config borderless_monocle    true
bspc config gapless_monocle       true

xrandr --output HDMI-0 --mode 1920x1080 --rate 75 &
picom -b --experimental-backends &
/usr/bin/dunst &
~/.fehbg &
~/.config/polybar/launch.sh &
mpd &
xsetroot -cursor_name left_ptr
